# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucketStatistics', '0002_bucketstatistics_avg_egg_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketstatistics',
            name='avg_egg_count',
            field=models.FloatField(default=0),
        ),
    ]
